### ISSUE TITLE
Incompatibility with kotlin 1.8.0

### ISSUE THREAD

**Issue by marekhanzlik** [Aallam/ulid-kotlin#27]
HI, i'm using kotlin 1.8.0 which should be supported since `ulid:1.2.0` but im getting error during compilation
```
/home/user/.gradle/caches/modules-2/files-2.1/com.aallam.ulid/ulid-kotlin-jvm/1.2.1/d268ad82180bbcf2ad843a41eb293e2446a436a9/ulid-jvm.jar!/META-INF/ulid.kotlin_module: 
Module was compiled with an incompatible version of Kotlin.
The binary version of its metadata is 1.8.0, expected version is 1.6.0.
```

im referencing it in `build.gradle.kts` as
```
    implementation("com.aallam.ulid:ulid-kotlin:1.2.1")
```

is there a way i can solve this or does it need to be fixed in ulid package?

Thanks

**Comment by aallam** [comment]
Hi @marekhanzlik, the library should indeed be compatible with kotlin `1.8.x`, but from the error, it seems like your kotlin plugin is `1.6.0`, could you please check it ?  it's in your `buildscript` or `plugins` section.

**Comment by marekhanzlik** [comment]
:facepalm: you are right, and i was so sure i'am already using kotlin 1.8 that i interpreted the message other way around ...
Sorry, and thanks!
