### ISSUE TITLE
ULID Crash On android 7 or Lower.

### ISSUE THREAD

**Issue by mrabbi-hishabee** [Aallam/ulid-kotlin#37]
![image](https://github.com/aallam/ulid-kotlin/assets/140314305/91a4e9f6-3a51-4b28-bb9a-6589240d5603)
![image](https://github.com/aallam/ulid-kotlin/assets/140314305/4cf35208-aba7-409d-b378-ce55c39beae5)

**Comment by aallam** [comment]
Hey @mrabbi-hishabee, the library uses Java 8 API, you need to enable [API desugaring](https://developer.android.com/studio/write/java8-support-table) to support older devices.

**Comment by mrabbi-hishabee** [comment]
solved. thanks .

follow this
android {
    defaultConfig {
        // Required when setting minSdkVersion to 20 or lower
        multiDexEnabled true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
dependencies {
    // For AGP 7.4+
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.3'
    // For AGP 7.3
    // coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.3'
    // For AGP 4.0 to 7.2
    // coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.9'
}
